# Generated by Django 3.0 on 2019-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sightings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.DecimalField(decimal_places=10, help_text='Latitude', max_digits=100)),
                ('Longitude', models.DecimalField(decimal_places=10, help_text='Longitude', max_digits=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique_Squirrel_ID', max_length=100)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], max_length=100)),
                ('Date', models.DateField(help_text='Date')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Other', 'Other')], default='Other', help_text='Age', max_length=10)),
                ('Primary_Fur_Color', models.CharField(choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray'), ('Other', 'Other')], default='Other', help_text='Primary_Fur_Color', max_length=30)),
                ('Location', models.CharField(choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('Other', 'Other')], default='Other', help_text='Location', max_length=30)),
                ('Specific_Location', models.CharField(help_text='Specific_Location', max_length=100)),
                ('Running', models.BooleanField(default=False, help_text='Running')),
                ('Chasing', models.BooleanField(default=False, help_text='Chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='Climbing')),
                ('Eating', models.BooleanField(default=False, help_text='Eating')),
                ('Foraging', models.BooleanField(default=False, help_text='Foraging')),
                ('Other_Activities', models.CharField(help_text='Other_Activities', max_length=100)),
                ('Kuks', models.BooleanField(default=False, help_text='Kuks')),
                ('Quaas', models.BooleanField(default=False, help_text='Quaas')),
                ('Moans', models.BooleanField(default=False, help_text='Moans')),
                ('Tail_flags', models.BooleanField(default=False, help_text='Tail_flags')),
                ('Tail_twitches', models.BooleanField(default=False, help_text='Tail_twitchs')),
                ('Approaches', models.BooleanField(default=False, help_text='Approaches')),
                ('Indifferent', models.BooleanField(default=False, help_text='Indifferent')),
                ('Runs_from', models.BooleanField(default=False, help_text='Runs_from')),
            ],
        ),
    ]
