# Generated by Django 2.2.7 on 2019-12-07 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='Date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Latitude',
            field=models.DecimalField(decimal_places=13, help_text='Latitude', max_digits=16),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='Longitude',
            field=models.DecimalField(decimal_places=13, help_text='Longitude', max_digits=16),
        ),
    ]
