# Generated by Django 2.2.7 on 2019-12-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0003_auto_20191207_1924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sightings',
            new_name='sightings_model',
        ),
    ]
